# permissions for end users to view credentialsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentconfigs-viewer-role
rules:
- apiGroups:
  - getporter.org
  resources:
  - agentconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - getporter.org
  resources:
  - agentconfigs/status
  verbs:
  - get
