# permissions for end users to edit agentactions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentaction-editor-role
rules:
- apiGroups:
  - getporter.org
  resources:
  - agentactions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - getporter.org
  resources:
  - agentactions/status
  verbs:
  - get
