# permissions for end users to view agentactions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentaction-viewer-role
rules:
- apiGroups:
  - getporter.org
  resources:
  - agentactions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - getporter.org
  resources:
  - agentactions/status
  verbs:
  - get
