# permissions for end users to edit agnetconfig.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentconfigs-editor-role
rules:
- apiGroups:
  - getporter.org
  resources:
  - agentconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - getporter.org
  resources:
  - agentconfigs/status
  verbs:
  - get
