# permissions for end users to view credentialsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: credentialset-viewer-role
rules:
- apiGroups:
  - porter.sh
  resources:
  - credentialsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - porter.sh
  resources:
  - credentialsets/status
  verbs:
  - get
