# permissions for end users to edit credentialsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: credentialset-editor-role
rules:
- apiGroups:
  - getporter.org
  resources:
  - credentialsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - getporter.org
  resources:
  - credentialsets/status
  verbs:
  - get
