# permissions for end users to edit porterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: porterconfig-editor-role
rules:
- apiGroups:
  - getporter.org
  resources:
  - porterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - getporter.org
  resources:
  - porterconfigs/status
  verbs:
  - get
