# permissions for end users to view porterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: porterconfig-viewer-role
rules:
- apiGroups:
  - getporter.org
  resources:
  - porterconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - getporter.org
  resources:
  - porterconfigs/status
  verbs:
  - get
