apiVersion: getporter.org/v1
kind: AgentConfig
metadata:
  name: agentconfig-sample
  labels:
    getporter.org/testdata: "true"
spec:
  porterRepository: ghcr.io/getporter/porter-agent
  porterVersion: canary
  serviceAccount: porter-agent
  volumeSize: 64Mi
  pullPolicy: Always
  installationServiceAccount: installation-agent
  plugins:
    - name: "kubernetes"