apiVersion: getporter.org/v1
kind: PorterConfig
metadata:
  name: porterconfig-sample
  labels:
    getporter.org/testdata: "true"
spec:
  verbosity: debug
  defaultSecretsPlugin: kubernetes.secrets
  defaultStorage: in-cluster-mongodb
  storage:
    - name: in-cluster-mongodb
      plugin: mongodb
      config:
        url: "mongodb://mongodb.porter-operator-system.svc.cluster.local"
