apiVersion: getporter.org/v1
kind: Installation
metadata:
  name: exec-outputs
  labels:
    getporter.org/testdata: "true"
spec:
  schemaVersion: 1.0.2
  namespace: operator
  name: outputs
  bundle:
    repository: getporter/exec-outputs
    version: 0.1.1
