apiVersion: getporter.org/v1
kind: Installation
metadata:
  name: hello-llama
  labels:
    getporter.org/testdata: "true"
spec:
  schemaVersion: 1.0.2
  namespace: operator
  name: mellama
  bundle:
    repository: getporter/hello-llama
    version: 0.1.1
  parameters:
    name: "Porter Operator"
